spring.application.name=AgendasDT
spring.datasource.url=${URL}
spring.datasource.username=${USER}
spring.datasource.password=${PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0
